### ISSUE TITLE
Ordering of autocomplete results for search

### ISSUE THREAD

**Issue by lineaba** [ucladevx/BQuest-Frontend#25]
Currently we do not get most ideal ordering of autocomplete suggestions, when a user searches for ambassadors. 
If a user searches for linguistics, it will not show up within the first 5 suggestions, because the BA is alphabetized later than linguistics and [blabla], so wee need to make sure the title (BA, BSc etc. is not part of the alphabetic ranking.

**Comment by marktai** [comment]
This is actually a backend issue. Can you move it?

**Comment by lineaba** [comment]
@marktai Did this get solved on backend, or should I still move it?

**Comment by lineaba** [comment]
looks like it did not get solved. I will move it
