### ISSUE TITLE
BUG cant scroll on profile page

### ISSUE THREAD

**Issue by lineaba** [ucladevx/BQuest-Frontend#37]
On the profile page scrolling is not possible. If a user adds a couple of lines of classes, this effectively mean that the save button disappears from screen. 
Implement scroll

![skaermbillede 157](https://user-images.githubusercontent.com/32916783/35774950-4ca52162-0933-11e8-86ea-d1c6ce049086.png)

**Comment by ramsgoli** [comment]
fixed!
