### ISSUE TITLE
BUG classes added get overwritten with next edit

### ISSUE THREAD

**Issue by lineaba** [ucladevx/BQuest-Frontend#39]
The data that the user have provided in the classes field gets overwritten, if the user have left the profile page, and then edits the field upon returning. 

The problem: add classes -> save -> leave profile page -> return to profile page -> edit classes (ALL CURRENT CLASSES DISAPPEAR) -> new classes overwrites existing data. 

The problem doesn't arise if the user saves classes, and then without leaving the profile page edits the field again.

**Comment by ramsgoli** [comment]
fixed!
