### ISSUE TITLE
Adjustment of card-size depending on screen width

### ISSUE THREAD

**Issue by lineaba** [ucladevx/BQuest-Frontend#57]
When a user is not in fullscreen, the layout of profile cards tends to be squeezed together unneccesarily. Add a min-width to these cards.
![skaermbillede 210](https://user-images.githubusercontent.com/32916783/38529342-214427de-3c19-11e8-8750-90980fce59b9.png)
Image is only an example, it happens in multiple different pages - make sure update is implemented everywhere it is necessary

**Comment by kevinkassimo** [comment]
# #59 
Fix attempted
