### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by lineaba** [ucladevx/BQuest-Frontend#78]
<img width="175" alt="bugcircle" src="https://user-images.githubusercontent.com/32916783/41010444-4b769910-68ec-11e8-9877-6a4c1b634062.png">

The d needs to be removed from recieved. Also, it currently says "long-awaiting" but since we don't yet have digests, there are no notifications for long-awaited messages, so this should be removed.

**Comment by DavidWChen** [comment]
"Become an Ambassador" on profile page

**Comment by DavidWChen** [comment]
Don't close the issue until it's merged into master.

**Comment by helarabawy** [comment]
Oh ok sorry!
