### ISSUE TITLE
Confusing bar titles

### ISSUE THREAD

**Issue by DavidWChen** [ucladevx/BQuest-Frontend#95]
![screen shot 2019-01-28 at 3 54 58 am](https://user-images.githubusercontent.com/23110056/51834890-8dcb2500-22b0-11e9-8331-072d4e46b461.png)
Ambassadors for the Search View and Settings for the Profile View is slightly confusing
 -possible to be fixed with onboarding feature

**Comment by jhan25** [comment]
Fixed with onboarding feature.
